---
- name: Copying files to remote
  hosts: all

  tasks:
  - name: Copy files
    copy: 
      src: /root/myfile.txt
      dest: /tmp/
      owner: paul
      group: paul
      mode: 0777
      backup: true   
