---
- name: File Module
  hosts: all

  tasks:
  - name: Creating a file
    file: 
      path: /tmp/newfile.txt
      state: absent
      owner: paul
      group: paul
      mode: 0764
  - name: Creating a directory
    file:
      path: /tmp/folder
      state: absent

