---
- name: Install and Start the service
  hosts: all

  tasks:
  - name: Installing nginx
    apt:
      name: nginx
      state: present
   
  - name: Starting nginx server
    service: 
      name: nginx
      state: started
      enabled: true

