---
- name: file and folder
  hosts: a2

  tasks:
  - name: creating a folder
    file:
      path: /tmp/script
      state: directory

  - name: creating a file
    file:
      name: test.sh
      mode: 0700
        
