---
- name: file and folder
  hosts: a1

  tasks:
  - name: creating a folder
    file:
      path: /tmp/script
      state: directory

  - name: creating a file
    file:
      path: /tmp/script/test.sh
      state: touch
      mode: 0700
        
